name: Auto Update

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Deciding to commit
        id: gatekeeper
        run: |
          HOUR=$(date -u +"%H")
          
          if [ "$HOUR" -eq "00" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            ROLL=$((RANDOM % 2))
            if [ $ROLL -eq 0 ]; then
              echo "should_run=true" >> $GITHUB_OUTPUT
            else
              echo "should_run=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Overwrite README content
        if: steps.gatekeeper.outputs.should_run == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          echo "# Dynamically Varied Update" > README.md
          echo "Last updated on: $(date -u +'%Y-%m-%d %T') UTC" >> README.md

      - name: Commit and Push changes
        if: steps.gatekeeper.outputs.should_run == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          
          git add README.md
          git diff-index --quiet HEAD || git commit -m "docs: dynamic auto-update README"
          git push
